Added Vertical Slider (Day 26)
benxene/7days-50projects pull request #101
Opened 2020-12-08 11:17 UTC by PranavGPR

closes #95 

**Screenshot**

![image](https://user-images.githubusercontent.com/51258030/101477279-07380200-3975-11eb-964e-e458324f5349.png)

2020-12-08 12:12 UTC, KrishnaMoorthy12 commented
I had concerns, I fixed them.

2020-12-08 12:12 UTC, KrishnaMoorthy12 approved these changes

2020-12-08 12:56 UTC, sank2000 requested changes
remove scroll bar 🚨

2020-12-08 17:41 UTC, Lakshmi2k1 approved these changes

2020-12-09 12:57 UTC, sank2000 approved these changes

2020-12-09 12:57 UTC, merged