added notes-app
benxene/7days-50projects pull request #28
Opened 2020-12-04 14:36 UTC by MohamedJakkariya

2020-12-04 16:42 UTC, sank2000 approved these changes

2020-12-04 17:59 UTC, KrishnaMoorthy12 requested changes
Change title and added pointer cursor for edit and delete icons

2020-12-04 18:51 UTC, KrishnaMoorthy12 approved these changes

2020-12-05 03:10 UTC, PranavGPR approved these changes

2020-12-05 03:11 UTC, merged